<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.thomsonreuters.ecp.cdap.examples</groupId>
    <artifactId>sampleappscala</artifactId>
    <version>2017.11-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Simple Scala CDAP Application</name>
    
        <scm>
        <connection>scm:git:ssh://git@github.com:myandrapati/maven-helloworld.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:myandrapati/maven-helloworld.git</developerConnection>
        <url>https://github.com/myandrapati/maven-helloworld</url>
        <tag>head</tag>
    </scm>



    <properties>
        <app.main.class>com.thomsonreuters.ecp.cdap.examples.SampleApp</app.main.class>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <scala.version>2.10.4</scala.version>
        <cdap.version>4.1.3</cdap.version>
        <spark.version>1.6.0</spark.version>
        <mvn.executable>mvn</mvn.executable>
        <slf4j.version>1.7.5</slf4j.version>
        <guava.version>18.0</guava.version>
        <junit.version>4.11</junit.version>
        <play.version>2.4.6</play.version>
        <ecp.message.version>0.38.0</ecp.message.version>
        <plpay.version>2.4.6</plpay.version>
        <logback.version>1.0.13</logback.version>
        <test.suite>**/SampleAppTestSuite.class</test.suite>
        <testcase.groups>com.tr.ecp.smoketest</testcase.groups>
        <tr.cdap.maven.plugin>5.0.25</tr.cdap.maven.plugin>
    </properties>

    <repositories>
        <!--Cloudera Repository -->
        <repository>
            <id>cloudera-repo-releases</id>
            <name>cloudera</name>
            <url>https://repository.cloudera.com/artifactory/repo/</url>
        </repository>
        <repository>
            <id>maven</id>
            <name>maven</name>
            <url>http://repo.maven.apache.org/maven2/</url>
        </repository>
    </repositories>



  

    <dependencies>
        <!-- Other dependencies -->

        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.version}</version>
        </dependency>

        <dependency>
            <groupId>co.cask.cdap</groupId>
            <artifactId>cdap-api</artifactId>
            <version>${cdap.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>co.cask.cdap</groupId>
            <artifactId>cdap-api-spark</artifactId>
            <version>${cdap.version}</version>
        </dependency>
        <dependency>
            <groupId>co.cask.cdap</groupId>
            <artifactId>cdap-client</artifactId>
            <version>${cdap.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>co.cask.cdap</groupId>
                    <artifactId>cdap-common</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>co.cask.cdap</groupId>
            <artifactId>cdap-common</artifactId>
            <version>${cdap.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.10</artifactId>
            <version>${spark.version}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>asm</groupId>
                    <artifactId>asm</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>0.7</version>
        </dependency>
        <dependency>
            <groupId>co.cask.cdap</groupId>
            <artifactId>cdap-unit-test</artifactId>
            <version>${cdap.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.takari.junit</groupId>
            <artifactId>takari-cpsuite</artifactId>
            <version>1.2.7</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${guava.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>${logback.version}</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
        <dependency>
            <groupId>com.tr.ecp</groupId>
            <artifactId>ecp-testing-core</artifactId>
            <version>2.0.7</version>
            <scope>test</scope>
        </dependency>
        <!-- Mandatory dependencies for using Spock -->
        <dependency>
            <groupId>org.spockframework</groupId>
            <artifactId>spock-core</artifactId>
            <version>1.0-groovy-2.4</version>
            <scope>test</scope>
        </dependency>
        <!-- Optional dependencies for using Spock -->
        <dependency> <!-- use a specific Groovy version rather than the one specified by spock-core -->
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.7</version>
            <scope>test</scope>
        </dependency>
        <dependency> <!-- enables mocking of classes (in addition to interfaces) -->
            <groupId>cglib</groupId>
            <artifactId>cglib-nodep</artifactId>
            <version>3.1</version>
            <scope>test</scope>
        </dependency>
        <dependency> <!-- enables mocking of classes without default constructor (together with CGLIB) -->
            <groupId>org.objenesis</groupId>
            <artifactId>objenesis</artifactId>
            <version>2.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>1.17</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20160212</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.8.4</version>
        </dependency>
        <dependency>
            <groupId>com.trgr.cobalt.infrastructure</groupId>
            <artifactId>ServiceRegistry</artifactId>
            <version>34.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.thomsonreuters.enterpriselogging</groupId>
            <artifactId>TRLoggingExtensions</artifactId>
            <version>37.3.4</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/config/*</include>
                    <include>**/*.xml</include>
                </includes>
            </resource>
        </resources>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>2.5.3</version>
                    <configuration>
                        <useReleaseProfile>false</useReleaseProfile>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-scm-plugin</artifactId>
                    <version>1.9.5</version>
                    <executions>
                        <execution>
                            <id>commit-next-version</id>
                            <phase>validate</phase>
                            <goals>
                                <goal>add</goal>
                                <goal>checkin</goal>
                            </goals>
                            <configuration>
                                <basedir>./</basedir>
                                <includes>pom.xml</includes>
                                <message>[ci-skip] Update build version to ${project.version}</message>
                                <!--<connectionType>connection</connectionType> -->
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.1</version>
                    <configuration>
                        <source>1.8</source>
                        <target>1.8</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.felix</groupId>
                    <artifactId>maven-bundle-plugin</artifactId>
                    <version>2.3.7</version>
                    <extensions>true</extensions>
                    <configuration>
                        <archive>
                            <manifest>
                                <mainClass>${app.main.class}</mainClass>
                            </manifest>
                        </archive>
                        <instructions>
                            <Embed-Dependency>*;inline=false;scope=compile|runtime</Embed-Dependency>
                            <Embed-Transitive>true</Embed-Transitive>
                            <Embed-Directory>lib</Embed-Directory>
                        </instructions>
                    </configuration>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>bundle</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>com.tr.ecp.cdap</groupId>
                    <artifactId>cdap-maven-plugin</artifactId>
                    <version>${tr.cdap.maven.plugin}</version>
                    <configuration>
                        <deploymentConfigurationPath>${deployment.file.path}</deploymentConfigurationPath>
                        <deploymentConfigurationType>${deployment.file.type}</deploymentConfigurationType>
                        <applicationConfigurationPath>${application.config.path}</applicationConfigurationPath>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.7.7.201606060606</version>
                    <executions>
                        <execution>
                            <id>default-prepare-agent</id>
                            <goals>
                                <goal>prepare-agent</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>default-report</id>
                            <phase>prepare-package</phase>
                            <goals>
                                <goal>report</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.5.0</version>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <!--<executable>${mvn.executable}</executable>
                            <arguments>
                              <argument>test</argument>
                              <argument>-Dtestcase.groups=com.tr.ecp.testing.IntegrationTest</argument>
                              &lt;!&ndash; for CI Box, cdap.username and cdap.password arguments should be provided through command line or mvn settings.xml &ndash;&gt;
                            </arguments>-->
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.scala-tools</groupId>
                <artifactId>maven-scala-plugin</artifactId>
                <version>2.15.2</version>
                <executions>
                    <execution>
                        <id>scala-compile-first</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>scala-test-compile</id>
                        <phase>process-test-resources</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <scalaVersion>${scala.version}</scalaVersion>
                </configuration>
            </plugin>
            <plugin>
                <!-- The gmavenplus plugin is used to compile Groovy code. To learn more about this plugin,
                visit https://github.com/groovy/GMavenPlus/wiki -->
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.14.1</version>
                <configuration>
                    <includes>
                        <include>${test.suite}</include>
                        <include>**/*Spec*.*</include>
                    </includes>
                    <!--<groups>${testcase.groups}</groups>-->
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>3.0.1</version>
            </plugin>
            <plugin>
                <groupId>com.tr.ecp.cdap</groupId>
                <artifactId>cdap-maven-plugin</artifactId>
                <version>${tr.cdap.maven.plugin}</version>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.7.7.201606060606</version>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>local</id>
            <activation>
                <activeByDefault>true</activeByDefault>
                <property>
                    <name>environment</name>
                    <value>local</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
        <profile>
            <id>lab</id>
            <activation>
                <property>
                    <name>environment</name>
                    <value>lab</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/lab-deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
        <profile>
            <id>sand</id>
            <activation>
                <property>
                    <name>environment</name>
                    <value>sand</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/sand-deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
        <profile>
            <id>dev</id>
            <activation>
                <property>
                    <name>environment</name>
                    <value>dev</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/dev-deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
        <profile>
            <id>upg</id>
            <activation>
                <property>
                    <name>environment</name>
                    <value>upg</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/upg-deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
        <profile>
            <id>ci</id>
            <activation>
                <property>
                    <name>environment</name>
                    <value>ci</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/ci-deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
        <profile>
            <id>demo</id>
            <activation>
                <property>
                    <name>environment</name>
                    <value>demo</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/demo-deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
        <profile>
            <id>qed</id>
            <activation>
                <property>
                    <name>environment</name>
                    <value>qed</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/qed-deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <activation>
                <property>
                    <name>environment</name>
                    <value>prod</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/prod-deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
        <profile>
            <id>qed-HDC</id>
            <activation>
                <property>
                    <name>environment</name>
                    <value>qed-HDC</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/qed-HDC-deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
        <profile>
            <id>qed-DTC</id>
            <activation>
                <property>
                    <name>environment</name>
                    <value>qed-DTC</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/qed-DTC-deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
        <profile>
            <id>reptest2-hdc</id>
            <activation>
                <property>
                    <name>environment</name>
                    <value>reptest2-hdc</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/reptest2-hdc-deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
        <profile>
            <id>reptest2-dtc</id>
            <activation>
                <property>
                    <name>environment</name>
                    <value>reptest2-dtc</value>
                </property>
            </activation>
            <properties>
                <deployment.file.path>src/main/resources/config/reptest2-dtc-deploy-config.yml</deployment.file.path>
                <deployment.file.type>yml</deployment.file.type>
                <application.config.path>src/main/resources/config/application-config.json</application.config.path>
            </properties>
        </profile>
    </profiles>
</project>
